package com.projectbypp.bookingmicroservice.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Getter
@Setter
@ToString
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "BookingDb")
@ApiModel(description = "Details about the Booking Model")
public class Booking {

    @Transient
    public static final String SEQUENCE_NAME = "booking_sequence";

    @Id
    @ApiModelProperty(notes = "The unique Booking Id which is autogenerated.")
    private int trainId;
    @ApiModelProperty(notes = "The unique Booking Id which is autogenerated.")
    private int userId;





    @Pattern(regexp = "^[A-Za-z -]+$", message = "Only alphabets allowed and - character allowed")
    @Size(min = 3, max = 20, message = "min 3 max 20 alphabets")
    @ApiModelProperty(notes = "The Train name.")
    private String trainName;




    @Pattern(regexp = "^[A-Za-z\\s]+$", message = "Only alphabets and spaces are allowed")
    @Size(min = 3, max = 15, message = "min 3 max 15 alphabets")
    @ApiModelProperty(notes = "The Passenger name.")
    private String passengerName;


    @Pattern(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,20}$"
            , message = "Email should be in the format abc@gmail.com")
    @ApiModelProperty(notes = "The email of the passenger.")
    private String email;


    @Pattern(regexp = "^\\d{10}$", message = "Phone number should be of 10 digits")
    @ApiModelProperty(notes = "The phone number of the passenger.")
    private String phone;





    @Pattern(regexp = "^[A-Za-z -]+$", message = "Only alphabets allowed and - character allowed")
    @Size(min = 3, max = 20, message = "min 3 max 20 alphabets")
    @ApiModelProperty(notes = "Source Station.")
    private String source;


    @Pattern(regexp = "^[A-Za-z -]+$", message = "Only alphabets allowed and - character allowed")
    @Size(min = 3, max = 20, message = "min 3 max 20 alphabets")
    @ApiModelProperty(notes = "Destination Station.")
    private String destination;

    @NotEmpty(message = "Required")
    @Pattern(regexp = "^[A-Za-z0-9 -]+$", message = "Only alphabets and digits allowed with space and \"-\". No other special characters allowed")
    @Size(min = 3, max = 20, message = "Min 3 and max 20 alphabets allowed")
    @ApiModelProperty(notes = "The Train Class Name.")
    private String className;

    @NotNull
    @Digits(integer = 1, fraction = 0)
    @ApiModelProperty(notes = "The total number of seats under the Train Class.")
    private int seats;


    @NotNull
    @Digits(integer = 1, fraction = 0)
    @ApiModelProperty(notes = "The total number of seats under the Train Class.")
    private int amount;



}